# noinspection SpringBootApplicationYaml
app:
  classification:
    processing:
      stopwords: classpath:/classification/stopwords_eng.dat
    opennlp:
      dl:
        model: classpath:/models/model_dl.onnx
        vocab: classpath:/models/vocab_dl.txt
        config: classpath:/models/config_dl.json
      me:
        model: classpath:/models/model_opennlp.7z
    corenlp:
      model: classpath:/models/model_corenlp.7z
      counter: classpath:/models/counter_corenlp.7z
      feature-weight-threshold: 0.25
    weka:
      model: classpath:/models/model_weka.7z
  extraction:
    languages:
      - eng
    tika:
      config-template-path: classpath:tika-config.xml.template
      tesseract:
        data-path: classpath:/tessdata
  processing:
    content-types:
      - application/epub+zip
      - application/msword
      - application/pdf
      - application/rtf
      - application/vnd.ms-word.document.macroenabled.12
      - application/vnd.ms-word.template.macroenabled.12
      - application/vnd.oasis.opendocument.flat.text
      - application/vnd.oasis.opendocument.graphics
      - application/vnd.oasis.opendocument.graphics-template
      - application/vnd.oasis.opendocument.image
      - application/vnd.oasis.opendocument.image-template
      - application/vnd.oasis.opendocument.text
      - application/vnd.oasis.opendocument.text-master
      - application/vnd.oasis.opendocument.text-template
      - application/vnd.oasis.opendocument.text-web
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
      - application/vnd.openxmlformats-officedocument.wordprocessingml.template
      - application/vnd.sun.xml.writer
      - application/vnd.wap.xhtml+xml
      - application/vnd.wordperfect; version=5.0
      - application/vnd.wordperfect; version=5.1
      - application/vnd.wordperfect; version=6.x
      - application/x-asp
      - application/x-fictionbook+xml
      - application/x-ibooks+zip
      - application/x-vnd.oasis.opendocument.graphics
      - application/x-vnd.oasis.opendocument.graphics-template
      - application/x-vnd.oasis.opendocument.image
      - application/x-vnd.oasis.opendocument.image-template
      - application/x-vnd.oasis.opendocument.text
      - application/x-vnd.oasis.opendocument.text-master
      - application/x-vnd.oasis.opendocument.text-template
      - application/x-vnd.oasis.opendocument.text-web
      - application/xhtml+xml
      - image/bmp
      - image/bpg
      - image/emf
      - image/gif
      - image/jp2
      - image/jpeg
      - image/jpx
      - image/jxl
      - image/png
      - image/tiff
      - image/webp
      - image/wmf
      - image/x-bpg
      - image/x-jbig2
      - image/x-ms-bmp
      - image/x-portable-pixmap
      - text/html
      - text/plain
  config:
    cors:
      max-age: 3600
      allowed-methods:
        - GET
        - POST
        - OPTIONS
      allowed-headers:
        - Origin
        - Accept
        - Content-Type
      exposed-headers:
        - Location
        - Content-Disposition
        - Content-Type

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# noinspection SpringBootApplicationYaml
context:
  initializer:
    classes: pl.piasta.newswise.BeansInitializer

spring:
  profiles:
    default: local
  webflux:
    multipart:
      max-disk-usage-per-part: 100MB
      max-in-memory-size: 0MB
      max-parts: 5
